package com.rental.notification.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_REMINDER,
    BOOKING_CANCELLED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    CHECK_IN_REMINDER,
    CHECK_OUT_REMINDER,
    REVIEW_REQUEST,
    MESSAGE_RECEIVED,
    BOOKING_REQUEST_RECEIVED,
    BOOKING_REQUEST_ACCEPTED,
    BOOKING_REQUEST_DECLINED

}