# Configuration spécifique à l'API Gateway
server:
  port: 8080


  application:
    name: api-gateway

  # Configuration Redis pour Rate Limiting
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# Configuration des routes

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service

        # Listing Service
        - id: listing-service
          uri: lb://listing-service
          predicates:
            - Path=/api/listings/**
          filters:
            - name: CircuitBreaker
              args:
                name: listingServiceCircuitBreaker
                fallbackUri: forward:/fallback/listing-service

        # Booking Service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingServiceCircuitBreaker
                fallbackUri: forward:/fallback/booking-service

        # Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payment-service

        # Messaging Service
        - id: messaging-service
          uri: lb://messaging-service
          predicates:
            - Path=/api/messages/**
          filters:
            - name: CircuitBreaker
              args:
                name: messagingServiceCircuitBreaker
                fallbackUri: forward:/fallback/messaging-service

        # Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification-service

        # Review Service
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - name: CircuitBreaker
              args:
                name: reviewServiceCircuitBreaker
                fallbackUri: forward:/fallback/review-service

        # Media Service
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - name: CircuitBreaker
              args:
                name: mediaServiceCircuitBreaker
                fallbackUri: forward:/fallback/media-service

        # Blockchain Service
        - id: blockchain-service
          uri: lb://blockchain-service
          predicates:
            - Path=/api/blockchain/**
          filters:
            - name: CircuitBreaker
              args:
                name: blockchainServiceCircuitBreaker
                fallbackUri: forward:/fallback/blockchain-service

# Configuration CORS
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# Configuration Resilience4J
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

logging:
  level:
    com.rental.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG

