# Configuration spécifique au Blockchain Service
server:
  port: 8089

spring:
  application:
    name: blockchain-service

# Configuration Blockchain
blockchain:
  network: sepolia
  chain-id: 11155111
  infura:
    url: https://sepolia.infura.io/v3/your-project-id
    project-id: your-project-id
    project-secret: your-project-secret
  contract:
    rental-platform:
      address: 0xYourContractAddress
      abi-path: contracts/RentalPlatform.json
  platform:
    wallet-address: 0xPlatformWalletAddress
    private-key: ${PLATFORM_PRIVATE_KEY:}
  transaction:
    gas-price-multiplier: 1.2
    max-retry: 3
    confirmation-blocks: 2
    timeout-seconds: 120

# Configuration Event Listener
event:
  listener:
    enabled: true
    poll-interval-seconds: 15
    from-block: latest

logging:
  level:
    com.rental.blockchainservice: DEBUG
    org.web3j: DEBUG