# Configuration spécifique au Listing Service
server:
  port: 8082

spring:
  application:
    name: listing-service

# Configuration pour upload de fichiers

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# Configuration de recherche
listing:
  search:
    max-results: 100
    default-radius-km: 50

logging:
  level:
    com.rental.listingservice: DEBUG