# Configuration spécifique au Messaging Service
server:
  port: 8085

spring:
  application:
    name: messaging-service

# Configuration WebSocket
websocket:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
  endpoint: /ws
  topic-prefix: /topic
  app-prefix: /app
  message-broker:
    relay-host: localhost
    relay-port: 61613

# Configuration des conversations
conversation:
  auto-archive-days: 90
  max-message-length: 2000

logging:
  level:
    com.rental.messagingservice: DEBUG
    org.springframework.messaging: DEBUG