# Configuration spécifique au Review Service
server:
  port: 8087

spring:
  application:
    name: review-service

# Configuration des avis
review:
  min-rating: 1
  max-rating: 5
  min-text-length: 10
  max-text-length: 2000
  moderation:
    enabled: true
    bad-words-filter: true
  reminder:
    send-after-checkout-days: 2

logging:
  level:
    com.rental.reviewservice: DEBUG